#!/usr/bin/env python3
"""Generate practical desktop UCM profiles for both Roland Capture models."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROLAND = ROOT / "ucm2" / "USB-Audio" / "Roland"


def profile(
    prefix: str,
    hw_out: int,
    hw_in: int,
    playback: list[tuple[str, tuple[int, ...]]],
    capture: list[tuple[str, tuple[int, ...]]],
) -> str:
    lines = [
        "# Generated by tools/generate_mono_ucm.py.",
        "# Inputs and unpaired outputs are mono; explicit L/R destinations are stereo.",
        "# At 192 kHz use the Pro Audio profile because the hardware channel count changes.",
        'Include.pcm_split.File "/common/pcm/split.conf"',
        "",
        "Macro [",
        "\t{",
        "\t\tSplitPCM {",
        f'\t\t\tName "{prefix}_mono_out"',
        "\t\t\tDirection Playback",
        "\t\t\tChannels 1",
        f"\t\t\tHWChannels {hw_out}",
    ]
    lines.extend(f"\t\t\tHWChannelPos{i} MONO" for i in range(hw_out))
    lines.extend(["\t\t}", "\t}", "\t{", "\t\tSplitPCM {"])
    lines.extend(
        [
            f'\t\t\tName "{prefix}_stereo_out"',
            "\t\t\tDirection Playback",
            "\t\t\tChannels 2",
            f"\t\t\tHWChannels {hw_out}",
        ]
    )
    lines.extend(
        f"\t\t\tHWChannelPos{i} {'FL' if i % 2 == 0 else 'FR'}"
        for i in range(hw_out)
    )
    lines.extend(["\t\t}", "\t}", "\t{", "\t\tSplitPCM {"])
    lines.extend(
        [
            f'\t\t\tName "{prefix}_mono_in"',
            "\t\t\tDirection Capture",
            "\t\t\tChannels 1",
            f"\t\t\tHWChannels {hw_in}",
        ]
    )
    lines.extend(f"\t\t\tHWChannelPos{i} MONO" for i in range(hw_in))
    lines.extend(["\t\t}", "\t}", "\t{", "\t\tSplitPCM {"])
    lines.extend(
        [
            f'\t\t\tName "{prefix}_stereo_in"',
            "\t\t\tDirection Capture",
            "\t\t\tChannels 2",
            f"\t\t\tHWChannels {hw_in}",
        ]
    )
    lines.extend(
        f"\t\t\tHWChannelPos{i} {'FL' if i % 2 == 0 else 'FR'}"
        for i in range(hw_in)
    )
    lines.extend(["\t\t}", "\t}", "]", ""])

    number = 1
    lines.extend(["# Playback destinations", ""])
    for endpoint, (comment, channels) in enumerate(playback):
        stereo = len(channels) == 2
        positions = ("FL", "FR") if stereo else ("MONO",)
        lines.extend(
            [
                f'SectionDevice."Line{number}" {{',
                f'\tComment "{comment}"',
                "",
                "\tValue {",
                f"\t\tPlaybackPriority {1000 - endpoint}",
                "\t}",
                "",
                "\tMacro.pcm_split.SplitPCMDevice {",
                f'\t\tName "{prefix}_{"stereo" if stereo else "mono"}_out"',
                "\t\tDirection Playback",
                f"\t\tHWChannels {hw_out}",
                f"\t\tChannels {len(channels)}",
            ]
        )
        for logical, (channel, position) in enumerate(zip(channels, positions)):
            lines.extend(
                [f"\t\tChannel{logical} {channel}", f"\t\tChannelPos{logical} {position}"]
            )
        lines.extend(["\t}", "}", ""])
        number += 1

    lines.extend(["# Capture sources", ""])
    for endpoint, (comment, channels) in enumerate(capture):
        stereo = len(channels) == 2
        positions = ("FL", "FR") if stereo else ("MONO",)
        lines.extend(
            [
                f'SectionDevice."Line{number}" {{',
                f'\tComment "{comment}"',
                "",
                "\tValue {",
                f"\t\tCapturePriority {1200 - endpoint}",
                "\t}",
                "",
                "\tMacro.pcm_split.SplitPCMDevice {",
                f'\t\tName "{prefix}_{"stereo" if stereo else "mono"}_in"',
                "\t\tDirection Capture",
                f"\t\tHWChannels {hw_in}",
                f"\t\tChannels {len(channels)}",
            ]
        )
        for logical, (channel, position) in enumerate(zip(channels, positions)):
            lines.extend(
                [f"\t\tChannel{logical} {channel}", f"\t\tChannelPos{logical} {position}"]
            )
        lines.extend(["\t}", "}", ""])
        number += 1
    return "\n".join(lines)


def main() -> None:
    octa_playback = [
        ("Main / Phones Output 1–2", (0, 1)),
        *((f"Output {i}", (i - 1,)) for i in range(3, 9)),
        ("Coaxial Output 9–10", (8, 9)),
    ]
    octa_capture = [
        *((f"Input {i}", (i - 1,)) for i in range(1, 9)),
        ("Coaxial Input 9–10", (8, 9)),
        ("Direct Mix A Input 11–12", (10, 11)),
    ]
    quad_playback = [
        ("Main / Phones Output 1–2", (0, 1)),
        ("Coaxial Output 3–4", (2, 3)),
    ]
    quad_capture = [
        ("Input 1", (0,)),
        ("Input 2", (1,)),
        ("Coaxial Input 3–4", (2, 3)),
        ("Direct Mix Input 5–6", (4, 5)),
    ]
    (ROLAND / "Octa-Capture-HiFi.conf").write_text(
        profile("oc", 10, 12, octa_playback, octa_capture), encoding="utf-8"
    )
    (ROLAND / "Quad-Capture-HiFi.conf").write_text(
        profile("qc", 4, 6, quad_playback, quad_capture), encoding="utf-8"
    )


if __name__ == "__main__":
    main()
